[build]
  publish = "."

[[redirects]]
  from = "/portal.html"
  to = "/portal.html"
  status = 200

[[redirects]]
  from = "/painel.html"
  to = "/painel.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200